# Generated by Django 4.1.3 on 2022-11-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='session_salary',
            field=models.FloatField(default=0.0),
        ),
    ]
