# Generated by Django 4.1.3 on 2022-11-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_session_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Adviser', 'Adviser'), ('Gradute', 'Gradute')], max_length=64),
        ),
    ]
